### ISSUE TITLE
Problem with Bello's included "OpenSans" font that causes corrupted characters to be shown

### ISSUE THREAD

**Issue by jmaeshawn** [Nessus85100/skin.bello.8#26]
I initially brought this issue up with the Kodi team over on their repository [https://github.com/xbmc/xbmc/issues/21710](https://github.com/xbmc/xbmc/issues/21710) but it seems that there's an issue with the OpenSans font included in Bello that causes corrupted characters to be displayed when used in Kodi v20 Nexus.

You can read more about it over on the Kodi repo, but it seems that the font has some problematic ligatures that make any title, synopsis, or system menu with the characters "ff" "fi" or "ffi" in it to show a garbled character instead of those letters.

Based on the detective work of a member of the Kodi team, a workaround for the problem was found by using a font editor to delete one of the font's subtables and exporting the modified font file, but I wanted to mention this here so you can hopefully find a more permanent solution (and check the Open Type features for other possible problems) by the time the Nexus version of Kodi gets officially released. 🤞

**Comment by Nessus85100** [comment]
I wrote a comment about this in [Kodi repo #21710 ](https://github.com/xbmc/xbmc/issues/21710).

I will leave this open as reminder for later.

Thanks
Nessus

**Comment by Nessus85100** [comment]
@jmaeshawn 
Since you already fix it and check it that it works fine, can you post a link to your modded OpenSans font? 

Or make a PR. Whatever is easy for you.

Cheers
Nessus
