### ISSUE TITLE
Update translation link

### ISSUE THREAD

**Issue by ArtyIF** [Nessus85100/skin.bello.8#29]
The current link in the repository leads to a non-existent Transifex team. According to commit history, it has been replaced with Weblate instead. I would like to contribute to this skin's localization, but I can't find the link.

**Comment by Nessus85100** [comment]
Yea, sorry about that. I've deleted the Bello project from transifex since Kodi has migrated translations from Transifex to Weblate for all skins.

If you want to contribute to Bello translations here is the link.... https://kodi.weblate.cloud/projects/kodi-add-ons-skins/skin-bello/

Thanks
Nessus

**Comment by Nessus85100** [comment]
Also you can check this link... https://forum.kodi.tv/showthread.php?tid=363132 so @gade01 can assign you to a language team.

**Comment by gade01** [comment]
@Nessus85100 
I think @ArtyIF is already part of the Russian translation team at Weblate.

Thanks so much for helping out with translations.
