### ISSUE TITLE
can a feature be added to hide the seekbar after a set period of time

### ISSUE THREAD

**Issue by liam8888999** [Nessus85100/skin.bello.8#5]
it would be good if the seekbar which appears when fast forwarding, rewinding, paused etc. would disappear after say 5 seconds so you could watch the video in fast forward if you wanted to without having the big black overlay in the way. this is a feature in the amber skin so can definitely be implemented

**Comment by Nessus85100** [comment]
That doesn't make any sense. If the ff/rw process will hide how you will see in which point you want to stop?. Sorry but i will not a feature for some people that they want to see videos in ff/rw. If you don't like the big black overlay then enable the simple seekbar layout from skin skin settings or from OSD menu... or you can get your hands dirty and code it by your self for your own personal use.
